### ISSUE TITLE
init.py issue 

### ISSUE THREAD

**Issue by ceramicSoda** [Sergey-Voskresenskiy/.dots#1]
Init script works incorrect. It doesn't seems scipt works in a proper way at all
It makes strange symlinks to non-existent directories instead of simple config swap or watever else "init" in filname stands for

You can always take mine from https://github.com/ceramicSoda/dotfiles
Zero dependencies, only bash needed ;D
Or just don't forget to change your own 
For your own safety <3

**Comment by Sergey-Voskresenskiy** [comment]
> <3

It is needed in order to make symbolic links to the necessary "places" that are in the folder with the script, so "programs" look for a directory with their configuration, and find the link and take the configuration from there.
